### ISSUE TITLE
Enable codecoverage

### ISSUE THREAD

**Issue by jo-mueller** [allysonryan/napari-toska#10]
To enable codecoverage checks for the repo, the owner (@allysonryan ) would have to enable it on [Codecoverage.io](https://app.codecov.io/). You can log in there with your github credentials and allow checking codecov your repos (i.e., this one). The repository would then show how much of its code is covered by automated tests, which is a useful quality indicator.

**Comment by allysonryan** [comment]
@jo-mueller Check back for update on this issue close of day 16.07.24

**Comment by jo-mueller** [comment]
Coverage is enabled (albeit not very high ^^")
