### ISSUE TITLE
tests/deployment of pages failing

### ISSUE THREAD

**Issue by allysonryan** [allysonryan/napari-toska#13]
@jo-mueller I merged the PR to deploy the pages, but there is a failure I do not understand. Can you have a look please? :)

**Comment by jo-mueller** [comment]
Hi @allysonryan ,

did you enable github pages for this repo? You can do so under the link in the error message (https://github.com/allysonryan/napari-toska/settings/pages)

**Comment by jo-mueller** [comment]
@allysonryan if that's something you'd want to look at together in a Zoom call, let me know :)

**Comment by jo-mueller** [comment]
@allysonryan just pinging you here again - do you think we could Zoom on this very quickly sometimes? The documentation links and everything we've written won't be easy to find in the current state :/
It's really a 5 minutes thing and I can take it from there 👍

**Comment by jo-mueller** [comment]
Fixed by 562f731fafd16029c311135eb1505df8a9e7d68c
