### ISSUE TITLE
Fix spine searching

### ISSUE THREAD

**Issue by jo-mueller** [allysonryan/napari-toska#3]
For some reason we run into indexing errors in the spine retrieval, but only in 3D. We should investigate this.

**Comment by allysonryan** [comment]
@jo-mueller Can I close this issue, or do we need to debug still?

**Comment by jo-mueller** [comment]
It may have been fixed by PR #5 but I'm not sure it's currently covered by tests. Or the test exists but is commented out. I'll check!
