### ISSUE TITLE
Push to PyPi

### ISSUE THREAD

**Issue by jo-mueller** [allysonryan/napari-toska#7]
Hi @allysonryan ,

with the package being public, the only thing left to do to turn it into a full-fledged plugin would be to push it to PyPi so that it's available through a simple `pip install napari-toska`. Would you mind if I publish it through my PyPi account?

**Comment by allysonryan** [comment]
Hi @jo-mueller.

I am fine with you pushing through your PyPi account. Do you need anything from me?

**Comment by jo-mueller** [comment]
Nah, just your consent ;)
