### ISSUE TITLE
Add jupyter book workflow 

### ISSUE THREAD

**Issue by jo-mueller** [allysonryan/napari-toska#8]
The documentation we built currently exists only locally. To automatically push it to a github page, the necessary github action needs to be set up and the deploy page has to be set up in the repository settings (can only be done by the owner).

To do so, follow these steps

- Go to repository `settings`
- Go to `Pages`
- Configure like in screenshot:

![Capture](https://github.com/allysonryan/napari-toska/assets/38459088/df072048-972e-47ea-972f-86e6c58f6cc9)

See also [jupyter book documentation](https://jupyterbook.org/en/stable/publish/gh-pages.html)

**Comment by allysonryan** [comment]
@jo-mueller I will work on this tomorrow :) let you know if I run into problems!

**Comment by jo-mueller** [comment]
Fixed as per our meeting yesterday :)
